In [ ]:
import pandas as pd

data = ["A","B", "C", "D", "E"]
se = pd.Series(data,
               index=[1,2,3,4,5])
print(se)
print("Index: ",se.index)
print("Values: ",se.values)

1    A
2    B
3    C
4    D
5    E
dtype: object
Index:  Index([1, 2, 3, 4, 5], dtype='int64')
Values:  ['A' 'B' 'C' 'D' 'E']

In [2]:
import pandas as pd

menu = {"커피": 2000,
        "라떼": 3500,
        "그린티": 3500,
        "차": 3000}
se = pd.Series(menu)
print(se)
print("Index: ",se.index)
print("Values: ",se.values)

커피     2000
라떼     3500
그린티    3500
차      3000
dtype: int64
Index:  Index(['커피', '라떼', '그린티', '차'], dtype='object')
Values:  [2000 3500 3500 3000]

In [8]:
import pandas as pd

data = [
    ['1000', 'A', 90.72],
    ['1001', 'B', 85.55],
    ['1002', 'C', 70.32],
    ['1003', 'D', 95.12],
    ['1004', 'E', 88.45]
]
df = pd.DataFrame(data,columns=['id', 'name', 'score'])
print(df)

     id name  score
0  1000    A  90.72
1  1001    B  85.55
2  1002    C  70.32
3  1003    D  95.12
4  1004    E  88.45

In [9]:
df.set_index("id", inplace=True)
print(df)
print("Index: ",df.index)
print("Values: ",df.values)
df.reset_index(inplace=True)
print(df)

     name  score
id
1000    A  90.72
1001    B  85.55
1002    C  70.32
1003    D  95.12
1004    E  88.45
Index:  Index(['1000', '1001', '1002', '1003', '1004'], dtype='object', name='id')
Values:  [['A' 90.72]
 ['B' 85.55]
 ['C' 70.32]
 ['D' 95.12]
 ['E' 88.45]]
     id name  score
0  1000    A  90.72
1  1001    B  85.55
2  1002    C  70.32
3  1003    D  95.12
4  1004    E  88.45

In [10]:
data = {"id": ['1000', '1001', '1002', '1003', '1004'],
        "name": ['A', 'B', 'C', 'D', 'E'],
        "score": [90.72, 85.55, 70.32, 95.12, 88.45]}
df = pd.DataFrame(data,index=[0,1,2,3,4])
print(df)

print("Index: ",df.index)
print("Values: ",df.values)
print("Columns: ",df.columns)
print("info:",df.info())

     id name  score
0  1000    A  90.72
1  1001    B  85.55
2  1002    C  70.32
3  1003    D  95.12
4  1004    E  88.45
Index:  Index([0, 1, 2, 3, 4], dtype='int64')
Values:  [['1000' 'A' 90.72]
 ['1001' 'B' 85.55]
 ['1002' 'C' 70.32]
 ['1003' 'D' 95.12]
 ['1004' 'E' 88.45]]
Columns:  Index(['id', 'name', 'score'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      5 non-null      object
 1   name    5 non-null      object
 2   score   5 non-null      float64
dtypes: float64(1), object(2)
memory usage: 160.0+ bytes
info: None

In [14]:
print(df[['id','name']])

     id name
0  1000    A
1  1001    B
2  1002    C
3  1003    D
4  1004    E

In [ ]:
print(df.loc[0,'name'])
print()
print(df.iloc[0:2])

A

     id name  score
0  1000    A  90.72
1  1001    B  85.55

In [30]:
data = {'id': ['1000', '1001', '1002', '1003', '1004'],
        'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
}
df = pd.DataFrame(data)
data = [
    ['1000',  90.72],
    ['1001',  85.55],
    ['1002',  70.32],
    ['1003',  95.12],
    ['1004',  88.45]
]
df2 = pd.DataFrame(data, columns=['id', 'score'])
df2.set_index('id', inplace=True)
df2["grade"] = ['A', 'B', 'C', 'A', 'B']

df = pd.merge(df,df2, how='inner', on='id')
df.set_index('id', inplace=True)

df

         name  score grade
id
1000    Alice  90.72     A
1001      Bob  85.55     B
1002  Charlie  70.32     C
1003    David  95.12     A
1004      Eva  88.45     B

In [41]:
data1 = { 'id' : ['1000', '1001', '1002', '1003', '1004', '1005'],
'name' : [ 'Steve', 'James', 'John', 'Jane', 'Paul', 'Tony'],
'gender' : ['M', 'M', 'M', 'F' ,"M", "M"]}
df1 = pd.DataFrame(data1)
data2 = { 'id' : ['1000', '1001', '1002', '1003', '1004', '1005'],
'score' : [90.72, 78.09, 98.43, 64.19, 81.30, 99.14],
'grade': ['A','C+','A+', 'C', 'B', 'A+' ]}
df2 = pd.DataFrame(data2)
df3 = pd.merge(df1, df2, on='id')
df3

     id   name gender  score grade
0  1000  Steve      M  90.72     A
1  1001  James      M  78.09    C+
2  1002   John      M  98.43    A+
3  1003   Jane      F  64.19     C
4  1004   Paul      M  81.30     B
5  1005   Tony      M  99.14    A+

In [42]:
dic = {"이름": ["철수", "영희", "민철", "경수", "동수", "소연", "민수"],
"학번" : [1000, 1001, 1002,1003,1004,1005,1006],
"지역": ["서울", "대전", "대구","부산", "서울", "제주","서울"],
"국어": [84, 80, 81, 80, 97, 96, 99],
"영어": [81, 91, 97, 99, 96, 80, 85],
"수학": [87, 72, 86, 76, 79, 90, 95],
"과학": [74, 83, 75, 71, 98, 73, 80] }

df = pd.DataFrame(dic)
df.set_index("학번", inplace=True)
df["총합"] = df.loc[:,["국어", "영어", "수학", "과학"]].sum(axis=1)
df["평균"] = df.loc[:,["국어", "영어", "수학", "과학"]].mean(axis=1)
df

      이름  지역  국어  영어  수학  과학   총합     평균
학번
1000  철수  서울  84  81  87  74  326  81.50
1001  영희  대전  80  91  72  83  326  81.50
1002  민철  대구  81  97  86  75  339  84.75
1003  경수  부산  80  99  76  71  326  81.50
1004  동수  서울  97  96  79  98  370  92.50
1005  소연  제주  96  80  90  73  339  84.75
1006  민수  서울  99  85  95  80  359  89.75

In [38]:
df["지역"].value_counts()

지역
서울    3
대전    1
대구    1
부산    1
제주    1
Name: count, dtype: int64